file(REMOVE_RECURSE "${ROOT}")
execute_process(COMMAND "${TEST_EXEC}" write "${ROOT}" RESULT_VARIABLE cold)
if(NOT cold EQUAL 0)
  message(FATAL_ERROR "cold cache process failed: ${cold}")
endif()
execute_process(COMMAND "${TEST_EXEC}" read "${ROOT}" RESULT_VARIABLE warm)
if(NOT warm EQUAL 0)
  message(FATAL_ERROR "warm cache process failed: ${warm}")
endif()
file(REMOVE_RECURSE "${ROOT}")
